### ISSUE TITLE
Match renaming diffs

### ISSUE THREAD

**Issue by jmatsushita** [yacut/git-split-diff-hyperclick#3]
Hi there,

I notice that the hyperlink is only present when the diff log is in the form
```
diff --git ...
index 123456..abcdef
```

It would be great to also match renaming diff log indexes of th form
```
diff --git ...
similarity index 83%
rename from ...
rename to ...
index 123456..abcdef
``` 

To split-diff files across renames.

Cheers,

Jun

**Comment by yacut** [comment]
Thanks for the issue. The renaming diff log index detection is available since v0.3.12.
